//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting_Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounting_Record()
        {
            this.Accounting_Record_Additional_Information = new HashSet<Accounting_Record_Additional_Information>();
            this.Accounting_Record_Support_Document = new HashSet<Accounting_Record_Support_Document>();
        }
    
        public int accounting_record_id { get; set; }
        public int customer_id { get; set; }
        public System.DateTime record_date { get; set; }
        public decimal amount { get; set; }
        public string record_type_name { get; set; }
        public int record_category_id { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounting_Record_Additional_Information> Accounting_Record_Additional_Information { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Record_Category Record_Category { get; set; }
        public virtual Record_Type Record_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounting_Record_Support_Document> Accounting_Record_Support_Document { get; set; }
    }
}
