//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting_Record_Support_Document
    {
        public int accounting_record_id { get; set; }
        public int customer_id { get; set; }
        public int document_file_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual Accounting_Record Accounting_Record { get; set; }
        public virtual Document_File Document_File { get; set; }
    }
}
