//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App_User()
        {
            this.App_Password = new HashSet<App_Password>();
        }
    
        public string user_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public string email { get; set; }
        public bool is_active { get; set; }
        public string user_role_name { get; set; }
        public int customer_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_Password> App_Password { get; set; }
        public virtual App_User_Role App_User_Role { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
