//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Retention_Table
    {
        public int customer_id { get; set; }
        public int retention_table_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual Retention_Table Retention_Table { get; set; }
    }
}
