//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Facesheet_Assigned_Employee = new HashSet<Facesheet_Assigned_Employee>();
        }
    
        public int employee_id { get; set; }
        public string employee_name { get; set; }
        public bool is_active { get; set; }
        public int customer_id { get; set; }
        public string employee_role_name { get; set; }
    
        public virtual Employee_Role Employee_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facesheet_Assigned_Employee> Facesheet_Assigned_Employee { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
