//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facesheet_Assigned_Employee
    {
        public int employe_id { get; set; }
        public int facesheet_id { get; set; }
        public int customer_id { get; set; }
        public string facesheet_role_name { get; set; }
    
        public virtual Facesheet Facesheet { get; set; }
        public virtual Facesheet_Role Facesheet_Role { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
