//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDashboard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GBDashboardEntities : DbContext
    {
        public GBDashboardEntities()
            : base("name=GBDashboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Facesheet> Facesheets { get; set; }
        public virtual DbSet<Facesheet_Additional_Information> Facesheet_Additional_Information { get; set; }
        public virtual DbSet<Facesheet_Assigned_Employee> Facesheet_Assigned_Employee { get; set; }
        public virtual DbSet<Facesheet_Key> Facesheet_Key { get; set; }
        public virtual DbSet<Facesheet_Role> Facesheet_Role { get; set; }
        public virtual DbSet<Facesheet_Source> Facesheet_Source { get; set; }
        public virtual DbSet<Facesheet_Status> Facesheet_Status { get; set; }
        public virtual DbSet<Facesheet_Support_Image> Facesheet_Support_Image { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Payment_Type> Payment_Type { get; set; }
        public virtual DbSet<Procedure> Procedures { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Role> Employee_Role { get; set; }
        public virtual DbSet<Accounting_Record> Accounting_Record { get; set; }
        public virtual DbSet<Accounting_Record_Additional_Information> Accounting_Record_Additional_Information { get; set; }
        public virtual DbSet<Accounting_Record_Support_Document> Accounting_Record_Support_Document { get; set; }
        public virtual DbSet<App_Password> App_Password { get; set; }
        public virtual DbSet<App_User> App_User { get; set; }
        public virtual DbSet<App_User_Role> App_User_Role { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Document_Type> Customer_Document_Type { get; set; }
        public virtual DbSet<Customer_Employee_Role> Customer_Employee_Role { get; set; }
        public virtual DbSet<Customer_Facesheet_Key> Customer_Facesheet_Key { get; set; }
        public virtual DbSet<Customer_Facesheet_Role> Customer_Facesheet_Role { get; set; }
        public virtual DbSet<Customer_Facesheet_Source> Customer_Facesheet_Source { get; set; }
        public virtual DbSet<Customer_Facesheet_Status> Customer_Facesheet_Status { get; set; }
        public virtual DbSet<Customer_Insurance> Customer_Insurance { get; set; }
        public virtual DbSet<Customer_Location> Customer_Location { get; set; }
        public virtual DbSet<Customer_Procedure> Customer_Procedure { get; set; }
        public virtual DbSet<Customer_Property> Customer_Property { get; set; }
        public virtual DbSet<Customer_Record_Category> Customer_Record_Category { get; set; }
        public virtual DbSet<Customer_Record_Type> Customer_Record_Type { get; set; }
        public virtual DbSet<Customer_Retention_Table> Customer_Retention_Table { get; set; }
        public virtual DbSet<Customer_Status> Customer_Status { get; set; }
        public virtual DbSet<Document_File> Document_File { get; set; }
        public virtual DbSet<Document_Type> Document_Type { get; set; }
        public virtual DbSet<Procedure_Category> Procedure_Category { get; set; }
        public virtual DbSet<Record_Category> Record_Category { get; set; }
        public virtual DbSet<Record_Key> Record_Key { get; set; }
        public virtual DbSet<Record_Type> Record_Type { get; set; }
        public virtual DbSet<Retention_Table> Retention_Table { get; set; }
        public virtual DbSet<Customer_Record_Key> Customer_Record_Key { get; set; }
    }
}
